/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e4e0d8',
        'secondary-container': '#f0e8db',
        'tertiary-fixed-dim': '#dcc48e',
        'background': '#faf6f0',
        'secondary-fixed': '#f0e8db',
        'on-primary-fixed': '#002110',
        'primary': '#4a7c59',
        'inverse-on-surface': '#f5f0e8',
        'surface-tint': '#4a7c59',
        'surface-container-highest': '#e4e0d8',
        'on-surface-variant': '#4a4e4a',
        'primary-container': '#78a886',
        'surface-bright': '#faf6f0',
        'surface-container': '#f0ece4',
        'primary-fixed': '#c8e8d0',
        'secondary-fixed-dim': '#d4ccbf',
        'surface-container-low': '#f5f1ea',
        'tertiary-fixed': '#f8e0a8',
        'on-secondary-container': '#5e5548',
        'on-surface': '#2e3230',
        'on-secondary-fixed-variant': '#4a4538',
        'error-container': '#ffdad8',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#eae6de',
        'on-error-container': '#690005',
        'inverse-primary': '#8ecf9e',
        'on-tertiary-fixed-variant': '#554020',
        'on-secondary': '#ffffff',
        'on-background': '#2e3230',
        'on-primary': '#ffffff',
        'tertiary': '#705c30',
        'primary-fixed-dim': '#8ecf9e',
        'inverse-surface': '#2e3230',
        'outline-variant': '#c4c8bc',
        'on-primary-fixed-variant': '#2a6038',
        'on-error': '#ffffff',
        'surface-dim': '#dbd7cf',
        'secondary': '#6b6358',
        'on-primary-container': '#d8f0de',
        'surface': '#faf6f0',
        'outline': '#74796e',
        'on-tertiary-container': '#554020',
        'tertiary-container': '#c4a66a',
        'error': '#b83230',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#1e1a13',
        'on-tertiary-fixed': '#221a05',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Literata', 'serif'],
        display: ['Literata', 'serif'],
        body: ['"Nunito Sans"', 'sans-serif'],
        label: ['"Nunito Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
